// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: emSX6SoS727kxhvsLiw8Ez
// Component: wf4HvmwkR2_t
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: emSX6SoS727kxhvsLiw8Ez/projectcss
import sty from "./PlasmicNewPage.module.css"; // plasmic-import: wf4HvmwkR2_t/css
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: vJwncxgMlKBz/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: EoBNRGNWPEZH/icon
import Arrow9Icon from "./icons/PlasmicIcon__Arrow9"; // plasmic-import: Lq9FXhH1Itp9/icon

createPlasmicElementProxy;

export const PlasmicNewPage__VariantProps = new Array();

export const PlasmicNewPage__ArgProps = new Array();

const $$ = {};

function PlasmicNewPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"aboutUs"}
            data-plasmic-override={overrides.aboutUs}
            className={classNames(projectcss.all, sty.aboutUs)}
          >
            <div
              data-plasmic-name={"rectangle70"}
              data-plasmic-override={overrides.rectangle70}
              className={classNames(projectcss.all, sty.rectangle70)}
            />

            <div
              data-plasmic-name={"image1"}
              data-plasmic-override={overrides.image1}
              className={classNames(projectcss.all, sty.image1)}
            />

            <div
              data-plasmic-name={"rectangle2"}
              data-plasmic-override={overrides.rectangle2}
              className={classNames(projectcss.all, sty.rectangle2)}
            />

            <div
              data-plasmic-name={"rectangle3"}
              data-plasmic-override={overrides.rectangle3}
              className={classNames(projectcss.all, sty.rectangle3)}
            />

            <div
              data-plasmic-name={"rectangle30"}
              data-plasmic-override={overrides.rectangle30}
              className={classNames(projectcss.all, sty.rectangle30)}
            />

            <div
              data-plasmic-name={"rectangle31"}
              data-plasmic-override={overrides.rectangle31}
              className={classNames(projectcss.all, sty.rectangle31)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ftDag
              )}
            >
              {"Our Story"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aoNf
              )}
            >
              {"We are a social commerce innovation\u00a0agency,"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__artUw
              )}
            >
              {
                "specialized in solving business challenges with creative\u00a0tech solutions and has been providing a wide range of\u00a0fresh\u00a0innovation services, from Innovation strategy, experience design to\u00a0digital platform development, to over 30 international and SET100\u00a0companies."
              }
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hcfEf
              )}
            >
              {
                "Because Omelet gives you that warm &\u00a0fuzzy feelings in your belly\u200b"
              }
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame2"}
              data-plasmic-override={overrides.frame2}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame2)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oQSa
                )}
              >
                {
                  "The Omelet was built with a vision to create positive impact in people's lives with innovation. What we do help change the way people work, live, learn, and play.\n\nWe\u2019re not only creating values for customers, but also for ourselves. A company can only grow when its team grows. Hence, our organization strives to ensure that our team's personal development is in tandem with company growth."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kMEpa
                )}
              >
                {"\u201cSky is not the limit, it's just the beginning\u201d"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame1"}
              data-plasmic-override={overrides.frame1}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame1)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__e8Hvl
                )}
              >
                {
                  "We\u2019re not only creating values for clients, but also for ourselves. A company can only grow when its team grows. Hence, our organization strives to ensure that our team's personal development is in tandem with company growth."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rTHoV
                )}
              >
                {"\u201cEmbrace fail, fail fast fail faster\u201d"}
              </div>
            </Stack__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fChZv
              )}
            >
              {"Our core values"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jr0L
              )}
            >
              {"Our kitchen (People)"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9MGm
              )}
            >
              {"Our cooks who served you only the best"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__y2HD
              )}
            >
              {"Gallery"}
            </div>
            <div
              data-plasmic-name={"rectangle38"}
              data-plasmic-override={overrides.rectangle38}
              className={classNames(projectcss.all, sty.rectangle38)}
            />

            <div
              data-plasmic-name={"rectangle42"}
              data-plasmic-override={overrides.rectangle42}
              className={classNames(projectcss.all, sty.rectangle42)}
            />

            <div
              data-plasmic-name={"rectangle44"}
              data-plasmic-override={overrides.rectangle44}
              className={classNames(projectcss.all, sty.rectangle44)}
            />

            <div
              data-plasmic-name={"rectangle45"}
              data-plasmic-override={overrides.rectangle45}
              className={classNames(projectcss.all, sty.rectangle45)}
            />

            <div
              data-plasmic-name={"rectangle43"}
              data-plasmic-override={overrides.rectangle43}
              className={classNames(projectcss.all, sty.rectangle43)}
            />

            <div
              data-plasmic-name={"rectangle39"}
              data-plasmic-override={overrides.rectangle39}
              className={classNames(projectcss.all, sty.rectangle39)}
            />

            <div
              data-plasmic-name={"rectangle40"}
              data-plasmic-override={overrides.rectangle40}
              className={classNames(projectcss.all, sty.rectangle40)}
            />

            <div
              data-plasmic-name={"rectangle46"}
              data-plasmic-override={overrides.rectangle46}
              className={classNames(projectcss.all, sty.rectangle46)}
            />

            <div
              data-plasmic-name={"rectangle41"}
              data-plasmic-override={overrides.rectangle41}
              className={classNames(projectcss.all, sty.rectangle41)}
            />

            <div
              data-plasmic-name={"image12"}
              data-plasmic-override={overrides.image12}
              className={classNames(projectcss.all, sty.image12)}
            />

            <div
              data-plasmic-name={"image13"}
              data-plasmic-override={overrides.image13}
              className={classNames(projectcss.all, sty.image13)}
            />

            <div
              data-plasmic-name={"image14"}
              data-plasmic-override={overrides.image14}
              className={classNames(projectcss.all, sty.image14)}
            />

            <div
              data-plasmic-name={"screencaptureTheomeletCo20240214205506"}
              data-plasmic-override={
                overrides.screencaptureTheomeletCo20240214205506
              }
              className={classNames(
                projectcss.all,
                sty.screencaptureTheomeletCo20240214205506
              )}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lkBif
              )}
            >
              {"That\u2019s all about us"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__igu8R
              )}
            >
              {"feel free to say Hi!"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mTSb
              )}
            >
              {
                "We are always open to work with an exceptional individuals. If you like what you're reading, feel free to reach out to us for a chat!"
              }
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jvAcQ
              )}
            >
              {"It is our mission to\u00a0\u200b"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mSyi7
              )}
            >
              {
                "create positive and measurable impact to our customers and communities with innovative solutions."
              }
            </div>
            <VectorIcon
              className={classNames(projectcss.all, sty.svg__xihi)}
              role={"img"}
            />

            <VectorIcon
              className={classNames(projectcss.all, sty.svg__wxNEk)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group"}
              data-plasmic-override={overrides.group}
              className={classNames(projectcss.all, sty.group)}
            >
              <div
                data-plasmic-name={"frame7"}
                data-plasmic-override={overrides.frame7}
                className={classNames(projectcss.all, sty.frame7)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"rectangle22"}
                    data-plasmic-override={overrides.rectangle22}
                    className={classNames(projectcss.all, sty.rectangle22)}
                  />
                ) : null}
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kPzMg
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uQEzc
                  )}
                >
                  {"Position"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hM8X
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  data-plasmic-name={"profile"}
                  data-plasmic-override={overrides.profile}
                  className={classNames(projectcss.all, sty.profile)}
                >
                  <div
                    data-plasmic-name={"rectangle23"}
                    data-plasmic-override={overrides.rectangle23}
                    className={classNames(projectcss.all, sty.rectangle23)}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"frame8"}
                data-plasmic-override={overrides.frame8}
                className={classNames(projectcss.all, sty.frame8)}
              >
                <div
                  data-plasmic-name={"rectangle24"}
                  data-plasmic-override={overrides.rectangle24}
                  className={classNames(projectcss.all, sty.rectangle24)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tQdLx
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zjlzl
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fZsG
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame9"}
                data-plasmic-override={overrides.frame9}
                className={classNames(projectcss.all, sty.frame9)}
              >
                <div
                  data-plasmic-name={"rectangle25"}
                  data-plasmic-override={overrides.rectangle25}
                  className={classNames(projectcss.all, sty.rectangle25)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sEe4K
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kwgAq
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dq7Hl
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame10"}
                data-plasmic-override={overrides.frame10}
                className={classNames(projectcss.all, sty.frame10)}
              >
                <div
                  data-plasmic-name={"rectangle26"}
                  data-plasmic-override={overrides.rectangle26}
                  className={classNames(projectcss.all, sty.rectangle26)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h4EnB
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fxpik
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cuJpU
                  )}
                >
                  {"Position"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"group2"}
              data-plasmic-override={overrides.group2}
              className={classNames(projectcss.all, sty.group2)}
            >
              <div
                data-plasmic-name={"frame11"}
                data-plasmic-override={overrides.frame11}
                className={classNames(projectcss.all, sty.frame11)}
              >
                <div
                  data-plasmic-name={"rectangle27"}
                  data-plasmic-override={overrides.rectangle27}
                  className={classNames(projectcss.all, sty.rectangle27)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mqvQt
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eL00B
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ud4A2
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame12"}
                data-plasmic-override={overrides.frame12}
                className={classNames(projectcss.all, sty.frame12)}
              >
                <div
                  data-plasmic-name={"rectangle28"}
                  data-plasmic-override={overrides.rectangle28}
                  className={classNames(projectcss.all, sty.rectangle28)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1GMgl
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jmPn
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g9X8F
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame13"}
                data-plasmic-override={overrides.frame13}
                className={classNames(projectcss.all, sty.frame13)}
              >
                <div
                  data-plasmic-name={"rectangle29"}
                  data-plasmic-override={overrides.rectangle29}
                  className={classNames(projectcss.all, sty.rectangle29)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yTgE1
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jkrYo
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qzJ5
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame14"}
                data-plasmic-override={overrides.frame14}
                className={classNames(projectcss.all, sty.frame14)}
              >
                <div
                  data-plasmic-name={"rectangle32"}
                  data-plasmic-override={overrides.rectangle32}
                  className={classNames(projectcss.all, sty.rectangle32)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eKvXa
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hzC4C
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hai7Q
                  )}
                >
                  {"Position"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"group3"}
              data-plasmic-override={overrides.group3}
              className={classNames(projectcss.all, sty.group3)}
            >
              <div
                data-plasmic-name={"frame15"}
                data-plasmic-override={overrides.frame15}
                className={classNames(projectcss.all, sty.frame15)}
              >
                <div
                  data-plasmic-name={"rectangle33"}
                  data-plasmic-override={overrides.rectangle33}
                  className={classNames(projectcss.all, sty.rectangle33)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fOu0Q
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ySuRo
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d54M
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame16"}
                data-plasmic-override={overrides.frame16}
                className={classNames(projectcss.all, sty.frame16)}
              >
                <div
                  data-plasmic-name={"rectangle34"}
                  data-plasmic-override={overrides.rectangle34}
                  className={classNames(projectcss.all, sty.rectangle34)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mf9TZ
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jDcy
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cfvxd
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame17"}
                data-plasmic-override={overrides.frame17}
                className={classNames(projectcss.all, sty.frame17)}
              >
                <div
                  data-plasmic-name={"rectangle35"}
                  data-plasmic-override={overrides.rectangle35}
                  className={classNames(projectcss.all, sty.rectangle35)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2EmrG
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z3Bt3
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__heEfE
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame18"}
                data-plasmic-override={overrides.frame18}
                className={classNames(projectcss.all, sty.frame18)}
              >
                <div
                  data-plasmic-name={"rectangle36"}
                  data-plasmic-override={overrides.rectangle36}
                  className={classNames(projectcss.all, sty.rectangle36)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nm8AN
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hrOrE
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Ub9J
                  )}
                >
                  {"Position"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"group4"}
              data-plasmic-override={overrides.group4}
              className={classNames(projectcss.all, sty.group4)}
            >
              <div
                data-plasmic-name={"frame19"}
                data-plasmic-override={overrides.frame19}
                className={classNames(projectcss.all, sty.frame19)}
              >
                <div
                  data-plasmic-name={"rectangle37"}
                  data-plasmic-override={overrides.rectangle37}
                  className={classNames(projectcss.all, sty.rectangle37)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zuGgj
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3WOKk
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__heiZs
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame20"}
                data-plasmic-override={overrides.frame20}
                className={classNames(projectcss.all, sty.frame20)}
              >
                <div
                  data-plasmic-name={"rectangle47"}
                  data-plasmic-override={overrides.rectangle47}
                  className={classNames(projectcss.all, sty.rectangle47)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y25T5
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__whC71
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bqe8M
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame21"}
                data-plasmic-override={overrides.frame21}
                className={classNames(projectcss.all, sty.frame21)}
              >
                <div
                  data-plasmic-name={"rectangle48"}
                  data-plasmic-override={overrides.rectangle48}
                  className={classNames(projectcss.all, sty.rectangle48)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tHoRg
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ntPwy
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l69Gp
                  )}
                >
                  {"Position"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame22"}
                data-plasmic-override={overrides.frame22}
                className={classNames(projectcss.all, sty.frame22)}
              >
                <div
                  data-plasmic-name={"rectangle49"}
                  data-plasmic-override={overrides.rectangle49}
                  className={classNames(projectcss.all, sty.rectangle49)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dXxT
                  )}
                >
                  {"Nickname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vHopj
                  )}
                >
                  {"Fullname Lastname"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v5XfT
                  )}
                >
                  {"Position"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"card"}
              data-plasmic-override={overrides.card}
              className={classNames(projectcss.all, sty.card)}
            >
              <div
                data-plasmic-name={"rectangle52"}
                data-plasmic-override={overrides.rectangle52}
                className={classNames(projectcss.all, sty.rectangle52)}
              />

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg__ly5Sf)}
                role={"img"}
              />

              <div
                data-plasmic-name={"professional"}
                data-plasmic-override={overrides.professional}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.professional
                )}
              >
                {"Professional"}
              </div>
            </div>
            <div
              data-plasmic-name={"card2"}
              data-plasmic-override={overrides.card2}
              className={classNames(projectcss.all, sty.card2)}
            >
              <div
                data-plasmic-name={"rectangle53"}
                data-plasmic-override={overrides.rectangle53}
                className={classNames(projectcss.all, sty.rectangle53)}
              />

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg___6GgXd)}
                role={"img"}
              />

              <div
                data-plasmic-name={"professional2"}
                data-plasmic-override={overrides.professional2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.professional2
                )}
              >
                {"Collaboration"}
              </div>
            </div>
            <div
              data-plasmic-name={"card3"}
              data-plasmic-override={overrides.card3}
              className={classNames(projectcss.all, sty.card3)}
            >
              <div
                data-plasmic-name={"rectangle54"}
                data-plasmic-override={overrides.rectangle54}
                className={classNames(projectcss.all, sty.rectangle54)}
              />

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg__itbq2)}
                role={"img"}
              />

              <div
                data-plasmic-name={"professional3"}
                data-plasmic-override={overrides.professional3}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.professional3
                )}
              >
                {"Growth Mindset"}
              </div>
            </div>
            <Arrow9Icon
              className={classNames(projectcss.all, sty.svg__c3KaY)}
              role={"img"}
            />

            <Arrow9Icon
              className={classNames(projectcss.all, sty.svg__u6Vxk)}
              role={"img"}
            />

            <Arrow9Icon
              className={classNames(projectcss.all, sty.svg___9LJxT)}
              role={"img"}
            />

            <Arrow9Icon
              className={classNames(projectcss.all, sty.svg__knrCt)}
              role={"img"}
            />

            <Arrow9Icon
              className={classNames(projectcss.all, sty.svg__i0Xjg)}
              role={"img"}
            />

            <Arrow9Icon
              className={classNames(projectcss.all, sty.svg__rUccF)}
              role={"img"}
            />

            <Arrow9Icon
              className={classNames(projectcss.all, sty.svg__vRcdp)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__eh4RF
              )}
            >
              {"Fade up\n1"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pTIkh
              )}
            >
              {"Fade up\n2"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nBfRk
              )}
            >
              {"Fade up\n1"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cwggf
              )}
            >
              {"Fade up\n1"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__k0QO8
              )}
            >
              {"Fade up\n2"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aml12
              )}
            >
              {"Fade up\n1"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__f1HiL
              )}
            >
              {"Fade up\n1"}
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame23"}
              data-plasmic-override={overrides.frame23}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame23)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dn0Mb
                )}
              >
                {"Get in touch"}
              </div>
            </Stack__>
            <div
              data-plasmic-name={"image2054"}
              data-plasmic-override={overrides.image2054}
              className={classNames(projectcss.all, sty.image2054)}
            />

            <div
              data-plasmic-name={"frame24"}
              data-plasmic-override={overrides.frame24}
              className={classNames(projectcss.all, sty.frame24)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jWZw
                )}
              >
                {"We serve fresh innovation for your better tomorrow"}
              </div>
            </div>
            <div
              data-plasmic-name={"image25"}
              data-plasmic-override={overrides.image25}
              className={classNames(projectcss.all, sty.image25)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "aboutUs",
    "rectangle70",
    "image1",
    "rectangle2",
    "rectangle3",
    "rectangle30",
    "rectangle31",
    "frame2",
    "frame1",
    "rectangle38",
    "rectangle42",
    "rectangle44",
    "rectangle45",
    "rectangle43",
    "rectangle39",
    "rectangle40",
    "rectangle46",
    "rectangle41",
    "image12",
    "image13",
    "image14",
    "screencaptureTheomeletCo20240214205506",
    "group",
    "frame7",
    "rectangle22",
    "profile",
    "rectangle23",
    "frame8",
    "rectangle24",
    "frame9",
    "rectangle25",
    "frame10",
    "rectangle26",
    "group2",
    "frame11",
    "rectangle27",
    "frame12",
    "rectangle28",
    "frame13",
    "rectangle29",
    "frame14",
    "rectangle32",
    "group3",
    "frame15",
    "rectangle33",
    "frame16",
    "rectangle34",
    "frame17",
    "rectangle35",
    "frame18",
    "rectangle36",
    "group4",
    "frame19",
    "rectangle37",
    "frame20",
    "rectangle47",
    "frame21",
    "rectangle48",
    "frame22",
    "rectangle49",
    "card",
    "rectangle52",
    "professional",
    "card2",
    "rectangle53",
    "professional2",
    "card3",
    "rectangle54",
    "professional3",
    "frame23",
    "image2054",
    "frame24",
    "image25"
  ],

  aboutUs: [
    "aboutUs",
    "rectangle70",
    "image1",
    "rectangle2",
    "rectangle3",
    "rectangle30",
    "rectangle31",
    "frame2",
    "frame1",
    "rectangle38",
    "rectangle42",
    "rectangle44",
    "rectangle45",
    "rectangle43",
    "rectangle39",
    "rectangle40",
    "rectangle46",
    "rectangle41",
    "image12",
    "image13",
    "image14",
    "screencaptureTheomeletCo20240214205506",
    "group",
    "frame7",
    "rectangle22",
    "profile",
    "rectangle23",
    "frame8",
    "rectangle24",
    "frame9",
    "rectangle25",
    "frame10",
    "rectangle26",
    "group2",
    "frame11",
    "rectangle27",
    "frame12",
    "rectangle28",
    "frame13",
    "rectangle29",
    "frame14",
    "rectangle32",
    "group3",
    "frame15",
    "rectangle33",
    "frame16",
    "rectangle34",
    "frame17",
    "rectangle35",
    "frame18",
    "rectangle36",
    "group4",
    "frame19",
    "rectangle37",
    "frame20",
    "rectangle47",
    "frame21",
    "rectangle48",
    "frame22",
    "rectangle49",
    "card",
    "rectangle52",
    "professional",
    "card2",
    "rectangle53",
    "professional2",
    "card3",
    "rectangle54",
    "professional3",
    "frame23",
    "image2054",
    "frame24",
    "image25"
  ],

  rectangle70: ["rectangle70"],
  image1: ["image1"],
  rectangle2: ["rectangle2"],
  rectangle3: ["rectangle3"],
  rectangle30: ["rectangle30"],
  rectangle31: ["rectangle31"],
  frame2: ["frame2"],
  frame1: ["frame1"],
  rectangle38: ["rectangle38"],
  rectangle42: ["rectangle42"],
  rectangle44: ["rectangle44"],
  rectangle45: ["rectangle45"],
  rectangle43: ["rectangle43"],
  rectangle39: ["rectangle39"],
  rectangle40: ["rectangle40"],
  rectangle46: ["rectangle46"],
  rectangle41: ["rectangle41"],
  image12: ["image12"],
  image13: ["image13"],
  image14: ["image14"],
  screencaptureTheomeletCo20240214205506: [
    "screencaptureTheomeletCo20240214205506"
  ],

  group: [
    "group",
    "frame7",
    "rectangle22",
    "profile",
    "rectangle23",
    "frame8",
    "rectangle24",
    "frame9",
    "rectangle25",
    "frame10",
    "rectangle26"
  ],

  frame7: ["frame7", "rectangle22", "profile", "rectangle23"],
  rectangle22: ["rectangle22"],
  profile: ["profile", "rectangle23"],
  rectangle23: ["rectangle23"],
  frame8: ["frame8", "rectangle24"],
  rectangle24: ["rectangle24"],
  frame9: ["frame9", "rectangle25"],
  rectangle25: ["rectangle25"],
  frame10: ["frame10", "rectangle26"],
  rectangle26: ["rectangle26"],
  group2: [
    "group2",
    "frame11",
    "rectangle27",
    "frame12",
    "rectangle28",
    "frame13",
    "rectangle29",
    "frame14",
    "rectangle32"
  ],

  frame11: ["frame11", "rectangle27"],
  rectangle27: ["rectangle27"],
  frame12: ["frame12", "rectangle28"],
  rectangle28: ["rectangle28"],
  frame13: ["frame13", "rectangle29"],
  rectangle29: ["rectangle29"],
  frame14: ["frame14", "rectangle32"],
  rectangle32: ["rectangle32"],
  group3: [
    "group3",
    "frame15",
    "rectangle33",
    "frame16",
    "rectangle34",
    "frame17",
    "rectangle35",
    "frame18",
    "rectangle36"
  ],

  frame15: ["frame15", "rectangle33"],
  rectangle33: ["rectangle33"],
  frame16: ["frame16", "rectangle34"],
  rectangle34: ["rectangle34"],
  frame17: ["frame17", "rectangle35"],
  rectangle35: ["rectangle35"],
  frame18: ["frame18", "rectangle36"],
  rectangle36: ["rectangle36"],
  group4: [
    "group4",
    "frame19",
    "rectangle37",
    "frame20",
    "rectangle47",
    "frame21",
    "rectangle48",
    "frame22",
    "rectangle49"
  ],

  frame19: ["frame19", "rectangle37"],
  rectangle37: ["rectangle37"],
  frame20: ["frame20", "rectangle47"],
  rectangle47: ["rectangle47"],
  frame21: ["frame21", "rectangle48"],
  rectangle48: ["rectangle48"],
  frame22: ["frame22", "rectangle49"],
  rectangle49: ["rectangle49"],
  card: ["card", "rectangle52", "professional"],
  rectangle52: ["rectangle52"],
  professional: ["professional"],
  card2: ["card2", "rectangle53", "professional2"],
  rectangle53: ["rectangle53"],
  professional2: ["professional2"],
  card3: ["card3", "rectangle54", "professional3"],
  rectangle54: ["rectangle54"],
  professional3: ["professional3"],
  frame23: ["frame23"],
  image2054: ["image2054"],
  frame24: ["frame24"],
  image25: ["image25"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewPage__ArgProps,
          internalVariantPropNames: PlasmicNewPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewPage";
  } else {
    func.displayName = `PlasmicNewPage.${nodeName}`;
  }
  return func;
}

export const PlasmicNewPage = Object.assign(
  // Top-level PlasmicNewPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    aboutUs: makeNodeComponent("aboutUs"),
    rectangle70: makeNodeComponent("rectangle70"),
    image1: makeNodeComponent("image1"),
    rectangle2: makeNodeComponent("rectangle2"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle30: makeNodeComponent("rectangle30"),
    rectangle31: makeNodeComponent("rectangle31"),
    frame2: makeNodeComponent("frame2"),
    frame1: makeNodeComponent("frame1"),
    rectangle38: makeNodeComponent("rectangle38"),
    rectangle42: makeNodeComponent("rectangle42"),
    rectangle44: makeNodeComponent("rectangle44"),
    rectangle45: makeNodeComponent("rectangle45"),
    rectangle43: makeNodeComponent("rectangle43"),
    rectangle39: makeNodeComponent("rectangle39"),
    rectangle40: makeNodeComponent("rectangle40"),
    rectangle46: makeNodeComponent("rectangle46"),
    rectangle41: makeNodeComponent("rectangle41"),
    image12: makeNodeComponent("image12"),
    image13: makeNodeComponent("image13"),
    image14: makeNodeComponent("image14"),
    screencaptureTheomeletCo20240214205506: makeNodeComponent(
      "screencaptureTheomeletCo20240214205506"
    ),
    group: makeNodeComponent("group"),
    frame7: makeNodeComponent("frame7"),
    rectangle22: makeNodeComponent("rectangle22"),
    profile: makeNodeComponent("profile"),
    rectangle23: makeNodeComponent("rectangle23"),
    frame8: makeNodeComponent("frame8"),
    rectangle24: makeNodeComponent("rectangle24"),
    frame9: makeNodeComponent("frame9"),
    rectangle25: makeNodeComponent("rectangle25"),
    frame10: makeNodeComponent("frame10"),
    rectangle26: makeNodeComponent("rectangle26"),
    group2: makeNodeComponent("group2"),
    frame11: makeNodeComponent("frame11"),
    rectangle27: makeNodeComponent("rectangle27"),
    frame12: makeNodeComponent("frame12"),
    rectangle28: makeNodeComponent("rectangle28"),
    frame13: makeNodeComponent("frame13"),
    rectangle29: makeNodeComponent("rectangle29"),
    frame14: makeNodeComponent("frame14"),
    rectangle32: makeNodeComponent("rectangle32"),
    group3: makeNodeComponent("group3"),
    frame15: makeNodeComponent("frame15"),
    rectangle33: makeNodeComponent("rectangle33"),
    frame16: makeNodeComponent("frame16"),
    rectangle34: makeNodeComponent("rectangle34"),
    frame17: makeNodeComponent("frame17"),
    rectangle35: makeNodeComponent("rectangle35"),
    frame18: makeNodeComponent("frame18"),
    rectangle36: makeNodeComponent("rectangle36"),
    group4: makeNodeComponent("group4"),
    frame19: makeNodeComponent("frame19"),
    rectangle37: makeNodeComponent("rectangle37"),
    frame20: makeNodeComponent("frame20"),
    rectangle47: makeNodeComponent("rectangle47"),
    frame21: makeNodeComponent("frame21"),
    rectangle48: makeNodeComponent("rectangle48"),
    frame22: makeNodeComponent("frame22"),
    rectangle49: makeNodeComponent("rectangle49"),
    card: makeNodeComponent("card"),
    rectangle52: makeNodeComponent("rectangle52"),
    professional: makeNodeComponent("professional"),
    card2: makeNodeComponent("card2"),
    rectangle53: makeNodeComponent("rectangle53"),
    professional2: makeNodeComponent("professional2"),
    card3: makeNodeComponent("card3"),
    rectangle54: makeNodeComponent("rectangle54"),
    professional3: makeNodeComponent("professional3"),
    frame23: makeNodeComponent("frame23"),
    image2054: makeNodeComponent("image2054"),
    frame24: makeNodeComponent("frame24"),
    image25: makeNodeComponent("image25"),
    // Metadata about props expected for PlasmicNewPage
    internalVariantProps: PlasmicNewPage__VariantProps,
    internalArgProps: PlasmicNewPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicNewPage;
/* prettier-ignore-end */
